### ISSUE TITLE
Which UI Library to use

### ISSUE THREAD

**Issue by floogulinc** [mn-pollinators/ar-simulation#14]
When I created this project I used [Material Web Components for Angular](https://trimox.github.io/angular-mdc-web/) rather than [Angular Material](https://material.angular.io/) that we are more used to. There are advantages to both but we should probably decide on one soon before we have too many customizations to the UI.

**Comment by michael-small** [comment]
Matt and I noticed this when we met today. We managed to get stuff done with MWC but it was a little different. I think that because of software design, not only would I likely be more comfortable with Material, but future maintainers as well.

**Comment by floogulinc** [comment]
Some things to consider:
- Assuming we want to continue with the design in our figma mockups, we will want a bottom app bar component. Neither library has one at the moment but it is definitely planned in MDC and there are already some examples someone made that we could probably pick up and use right away. See https://github.com/material-components/material-components-web/issues/2659
- For auth in Firebase, there are various libraries to provide some of the basic UI. 
  - The [official UI library from Google](https://github.com/firebase/firebaseui-web) but without any specific Angular support so it would be work to integrate it
  - A [simple Angular library](https://github.com/RaphaelJenni/firebaseui-angular) for the official UI
  - A [more complex Angular library](https://github.com/AnthonyNahas/ngx-auth-firebaseui) that uses Angular Material and requires it. If we want to use this library it could be a reason to choose Angular Material.

**Comment by UtkarshKr007** [comment]
I would also prefer Angular Material. In terms of UI libraries, both FirebaseUI_Angular and ngx-auth-fairebaseui provide a lot more features. FirebaseUI-Angular has a troubleshoot section on their main page that exposes a few problems we might run into and how to go around them.

**Comment by floogulinc** [comment]
When you say "in terms of UI libraries," do you mean the authentication UI libraries or UI libraries in general?

**Comment by UtkarshKr007** [comment]
I meant the authentication UI like the "Sign in with google" button, etc

**Comment by floogulinc** [comment]
It looks like we have decided to continue with Angular MDC.
