### ISSUE TITLE
App Name

### ISSUE THREAD

**Issue by floogulinc** [mn-pollinators/ar-simulation#6]
We will eventually have to come up with a better name for the app. Let's discuss potential ideas here.

**Comment by floogulinc** [comment]
current ideas:
- Bee the Bee
- Bee a Bee

**Comment by kklamberty** [comment]
"Be a bee" or "Be the bee" were the original ideas.
- SimBee
- BeeSim
- BeezBuzz

**Comment by kklamberty** [comment]
We have decided to name the app Buzz About.
